### ISSUE TITLE
Omp crash

### ISSUE THREAD

**Issue by FabioLolix** [TheWiseNoob/OpenMusicPlayer#4]
Hello, I have just seen, compiled and installed omp from the AUR, when launched it crash instanly

> $ omp
find() setting name: output.sink
find() setting name: output.sink
find() setting name: playback.volume
find() setting name: playback.volume
(omp:19455): GLib-GObject-WARNING **: value "100,000000" of type 'gdouble' is invalid or out of range for property 'volume' of type 'gdouble'
find() setting name: replaygain.pre_amp
find() setting name: replaygain.pre_amp
find() setting name: replaygain.fallback_gain
find() setting name: replaygain.fallback_gain
find() setting name: replaygain.gain_type
find() setting name: replaygain.gain_type
terminate called after throwing an instance of 'Glib::FileError'
Annullato (core dump creato)

**Comment by TheWiseNoob** [comment]
Sorry, I need to add an install script to this GitHub. The file error is because it's looking for two image files in a directory where they are not. The PKGBUILD on AUR moves them there, but I don't have an install script on here yet.

Manually moving  Images/No_Cover.svg to /usr/share/pixmaps/no_cover.png"
and Images/Icon_Small.png /usr/share/pixmaps/omp.png" will fix this crash.

**Comment by TheWiseNoob** [comment]
Thank you, Fabio! I fixed the problem. Should work now. Part of the code was still looking for the old location of the no cover image file.
